pkgtype: lib
summary: GSettings schemas for desktop components
git-url: https://gitlab.gnome.org/GNOME/gsettings-desktop-schemas
src-url: https://download.gnome.org/sources/gsettings-desktop-schemas/48/gsettings-desktop-schemas-48.0.tar.xz
src-sha: e68f155813bf18f865a8b2c8e9d473588b6ccadcafbb666ab788857c6c2d1bd3
license: LGPL-2.1-or-later
dep-pkg: glib
install: mesonw -Dintrospection=false
