summary: Configuration file processing library
web-url: https://hyperrealm.github.io/libconfig/
src-url: https://github.com/hyperrealm/libconfig/releases/download/v1.7.3/libconfig-1.7.3.tar.gz
src-sha: 545166d6cac037744381d1e9cc5a5405094e7bfad16a411699bcff40bbb31ee7
license: LGPL-2.1-or-later
bsystem: configure
