summary: XML-based font configuration library
web-url: https://wiki.freedesktop.org/www/Software/fontconfig
git-url: https://gitlab.freedesktop.org/fontconfig/fontconfig
src-url: https://gitlab.freedesktop.org/fontconfig/fontconfig/-/archive/2.18.1/fontconfig-2.18.1.tar.gz
src-sha: e9309564717b6301230112b173f36c288489479d381d2f0add1210ca5b16ba7e
license: MIT
dep-pkg: libfreetype libexpat libiconv
dep-upp: gperf python3

install: |
    mesonw \
        -Dnls=disabled \
        -Diconv=enabled \
        -Dtests=disabled \
        -Dtools=disabled
