pkg_set summary "Maintained ctags implementation"
pkg_set git.url "https://github.com/universal-ctags/ctags.git"
pkg_set bsystem "autogen"
pkg_set dep.cmd "pkg-config"
pkg_set dep.pkg "jansson libyaml libxml2"
